name=ADXL366_WE
version=3.0.6
author=Wolfgang Ewald <wolfgang.ewald@wolles-elektronikkiste.de>
maintainer=Wolfgang Ewald <wolfgang.ewald@wolles-elektronikkiste.de>
sentence=A library for the ADXL366 and ADXL367 accelerometer 
paragraph=An easy-to-use library with lots of example sketches. It allows to use most of the features of the ADXL366 including all interrupts and FIFO modes.
category=Sensors
url=https://github.com/wollewald/ADXL366_WE
architectures=*
includes=ADXL366_WE.h
